### ISSUE TITLE
Multiple spawns of story NPCs with Menyoo installed

### ISSUE THREAD

**Issue by Hundr** [attitus3/OpenVHook#7]
Using: EGS GTA V (1868.4), Menyoo Trainer v1.3.0, ScriptHookV.dll (your version), and dinput8.dll

Issue: Multiple spawns of the same NPC "Floyd", one after the other, non-stop. The game is spawning the NPC at the safehouse, under the bedrooms, and around the perimeter of the safehouse, in the streets.  

When I switch to a different ScriptHookV.dll, created by different author (Kenny Wall), the issue does not happen.

**Comment by 212antt** [comment]
Did you try using my plugin again to see if this happened again?

**Comment by Hundr** [comment]
Yes this was occurring with your latest build. It was then that I switched to a different .DLL from a Kenny Wall (gtaforums) and the continous PED/NPC spawning did not happen again.
Posted here:
https://gtaforums.com/topic/717612-v-scriptnative-documentation-and-research/page/39/?tab=comments#comment-1071221925

**Comment by 212antt** [comment]
I meant did you switch back to my dll and see if the continuous spawning occurred?

**Comment by Hundr** [comment]
Yes I have been able to reproduce this issue, even with progressing further in the story. When I return to Trevor's safehouse, Flyod PED's continue to spawn I have attached a screenshot:

![gtav-ped-1](https://user-images.githubusercontent.com/36519296/82842852-2378c380-9ea9-11ea-9aa2-63f700d1ddb4.PNG)

**Comment by Hundr** [comment]
does not happen without mods and with the other .dll

**Comment by Hundr** [comment]
![gtav-mission-1](https://user-images.githubusercontent.com/36519296/82842961-76527b00-9ea9-11ea-847d-18085a0d904d.PNG)

**Comment by 212antt** [comment]
Should have been fixed with commit 09dfec4, but it requires testing.

**Comment by attitus3** [comment]
I'm currently investigating the cause of this issue, as recently I've been able to replicate it.

**Comment by DwemerEngineer** [comment]
I'm going to close this out as it should of been resolved with the pools improvements, any other issues involving pools will be merged into a new issue for better clarity about the state of the project.
